### ISSUE TITLE
Creating a process with the same name as a submodel results in inconsistent SemSim OWL files

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#144]
I noticed this when I created the process "Dehydrogenase flux" for the beard_2005 model. I was annotating the CellML version and it has a component called "Dehydrogenase_flux".  When the SemSim model gets saved as an OWL file, an underscore is added to the process name in the process's URI, and so the process and the submodel get conflated. This results in an inconsistent ontology because the same individual is classified as both a process and a submodel. 

We should not allow users to create processes that have the same names as data structures, custom physical entities or submodels.

**Comment by thompsct** [comment]
Is this still a problem?

**Comment by maxneal** [comment]
Yes.

**Comment by maxneal** [comment]
Fixed in commit 3c416264fb45d082026f7502b33feb9efd2ba702
