### ISSUE TITLE
Allow user to string-search for nodes in Stage graphs

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#166]
As in the old Extractor, we need a way to search for nodes on the Stage.

Whereas the old search tool only highlighted nodes whose labels matched the input string, I'd like it if we could search over the free-text descriptions of codewords and submodels as well as the node labels.  So if someone opens up a new model and they don't know which codeword represents hexokinase activity, they can search for "hexokinase" and the search tool will return the node that represents hexokinase activity. 

Note that search results should be presented as a list that the user then selects from. After the user selects from the list, the set of nodes associated with the selected item should  be highlighted on the Stage. (This is different behavior than the previous search tool where search results were just indicated by node label highlighting.)

Would be nice if the user could also toggle whether to search over the free-text definitions or not.

Also, the search tool should be available whenever there is a node on the Stage. i.e. whether the user is performing a merge, extraction, whatever.

**Comment by GrahamKim** [comment]
Fixed in StageMerger branch.
