### ISSUE TITLE
Several issues with deleting terms in the Annotation Reference Library

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#193]
1) In the "Edit term" tab you can select multiple terms but when you hit the red X to delete them, only the 1st one in the list is deleted.

2)  SemGen doesn't recognize that the model has been edited once the user has removed one of these terms. Doesn't prompt for a save when you close.

3) The reference terms aren't actually deleted from the model. If you save out the model after removing the terms then re-open, the terms are still there.

**Comment by thompsct** [comment]
Finally fixed this in the extractor.

**Comment by maxneal** [comment]
Issue 1 still exists.
When attempt to save out jiang as new model after deleting ADP from reference entities, SG throws exception and model isn't saved out.

**Comment by maxneal** [comment]
Fixed in StageExtractor branch
