### ISSUE TITLE
Fix bug associated with SBML-based extraction and export

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#216]
To reproduce:

- Load Jiang model from original SBML code, extract one of the reactions (e.g. v15) from the PhysioMap visualization
- Attempt to export to a new SBML model
- Exception thrown

**Comment by thompsct** [comment]
After making a few changes, I've extracted v15 several ways and included random inputs and am no longer seeing the error. (ExtractorBranch)

**Comment by maxneal** [comment]
Confirmed that exporting the extraction doesn't throw the exception anymore, and the extracted model is being saved out.
