### ISSUE TITLE
Indicate mapping type in semantic resolution dialog mappings

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#224]
Currently there's no way to distinguish whether a data structure mapping is between semantically equivalent data structures or semantically _similar_ data structures. You can distinguish a manual mapping by the presence of the "Remove" button under the "Preview" button, but the mapping type should be made explicit for all data structure mappings in the dialog.

**Comment by GrahamKim** [comment]
Move the mapping type label to the left side of the panel header.

**Comment by maxneal** [comment]
Added in StageMerger
