### ISSUE TITLE
Icons in Active Task buttons are horizontally stretched

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#232]

**Comment by thompsct** [comment]
Not really seeing this. The icons are set at 30px for width and height.

**Comment by maxneal** [comment]
I see it in both the StageMerger and StageExtractor branches on Mac and Windows. Those icons are supposed to be used at 20x20 resolution. Maybe try bumping the width and height down to 20px.

**Comment by maxneal** [comment]
Fixed in master
