### ISSUE TITLE
Extractions produce empty models

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#237]
Sometimes when selecting a set of nodes in a model, then right clicking and selecting "Extract Selected", the resulting model doesn't contain anything. Double clicking it shows an empty model and selecting the different visualizations don't do anything.

**Comment by thompsct** [comment]
I'm having problems reproducing this. Do you know of a reliable way to trigger it?

**Comment by maxneal** [comment]
This is consistently reproducing the problem on my windows machine:

1) Open the CardiovascularDynamics model into a Project tab, click the Dependencies view.
2) Select the following codewords using the node selection tool: VrestRAd, VrestRAs, EminRA and EmaxRA (note these are all constitutive codewords)
3) Right click on one of the selected nodes and select "Extract Selected"
4) Name the new model and attempt to visualize its contents. 

Hope that reproduces it on your end.

Might have something to do with all the nodes being constitutive.

**Comment by thompsct** [comment]
Yep, that does it.

**Comment by thompsct** [comment]
I just realized those would be orphan nodes and are likely being hidden.

**Comment by maxneal** [comment]
They should be visible, though, even if they are all orphans. Right? Or am I missing something?
