### ISSUE TITLE
Dependency visualizations don't show model-model connections for Pandit-Hinch merge

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#245]
- Perform pandit-hinch merge
- Save merged model out as owl file
- Add merged model to project
- Activate the dependency view

There are three disconnected graphs, once you let the nodes separate enough. It should be a single interconnected graph. Works OK for CV+BARO and Jiang-Pedersen merging tasks.

Weird thing is that when you re-open the merged model that was saved out and visualize it, it's a single interconnected graph.

**Comment by thompsct** [comment]
This is because of how objects are handled in the merging algorithms vs how they're encoded for visualization. I've been meaning to bring the merger in line with the how the stage encodes models. It will take a little bit of time though.

**Comment by thompsct** [comment]
I've gone with the workaround of saving out a temporary file and reloading. It should display correctly now.
