### ISSUE TITLE
Hiding Entity nodes on Physiomap breaks the visualization. Hiding Unspecified ndoes on Physiomap doesn't actually hide Unspecified nodes.

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#247]

**Comment by maxneal** [comment]
You can use the CV model to reproduce both of these bugs.

**Comment by GrahamKim** [comment]
@maxneal This should be fixed in the master branch. Please give it a test and let me know!

**Comment by maxneal** [comment]
Looks like the visualizations respond correctly now, but in the node key the buttons move to the bottom of their groups. Can we keep the positions of the buttons static and just gray them out?
