### ISSUE TITLE
Extracting unselected nodes in a physiomap extracts entire model

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#249]
To reproduce:

- Load CV model
- View PhysioMap
- Select a subset of nodes, right click and select "Extract unselected"
- The extracted model will contain all physiomap nodes

**Comment by thompsct** [comment]
This happens because the dependency nodes containing the composite or process are removed, but the codewords are retained if any remaining nodes uses them as inputs. The semantics are thus preserved as inputs for merging. I'm not sure what to do about it beyond directly modifying any equations using the codewords.

**Comment by maxneal** [comment]
I don't think I understand the problem. Why isn't extracting the UNselected nodes just a matter of determining which nodes in the graph are unselected, then sending that set to the same functions used by the "Extract Selected" feature? If Extract Selected works, then why don't we just do that?

**Comment by thompsct** [comment]
It's removing all nodes with the selected annotation, but if a deleted node is used in a kept equation, then the node is turned into an interface. The semantics of that node are kept.

**Comment by thompsct** [comment]
My latest changes seem to have fixed the problem. The exclude was adding a process and all of its participants. Also, any entities not attached to a process weren't being displayed and couldn't be excluded.

**Comment by maxneal** [comment]
I've confirmed that you get the same content if you extract a set of nodes or extract the unselected nodes using the set's complement.

But it look like you've changed things so that the PhysioMap shows physical entities that are not associated with any process. I might be wrong, but I thought we decided to hide those nodes and only show entities that are participants in a process.

**Comment by thompsct** [comment]
Think I got it this time. The converse test is producing identical results.

**Comment by maxneal** [comment]
OK looks like this is working now.
