### ISSUE TITLE
Extracting a mix of submodels and dependency nodes sometimes fails with "Uncaught TypeError: Cannot read property 'graph' of null" in dependencyNode.js:78

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#250]

**Comment by thompsct** [comment]
Which model and components is this failing for?

**Comment by thompsct** [comment]
This seems to be tied to the regex and '+' issue I noted in the issue immediately above this one. The extraction routines are failing to correctly identify strings, and therefore nodes, as equivalent.

**Comment by thompsct** [comment]
Fixing the '+' issue appears to have also fixed this issue.
