### ISSUE TITLE
Manual mapping during semantic resolution throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#251]
Use Pandit-Hinch merge to reproduce. Attempt to manually map these codewords:

Hinch: convert_hinch.I_LCC
Pandit: L_type_Ca_channel.i_Ca_L

**Comment by thompsct** [comment]
Fixed

**Comment by maxneal** [comment]
Is this fixed in the master branch? I still get the same error when I try to do this.

**Comment by thompsct** [comment]
Fixed for real this time.
