### ISSUE TITLE
Cancelling merge save-out should just close the save dialog

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#253]
Currently when you press the green "Merge" button, then cancel out of the save dialog that shows up, SG takes you to the interface for visualizing the merged model. It should just kill the dialog so you end up right where you were before you hit the "Merge" button.

**Comment by thompsct** [comment]
Canceling the save still results in a completed merge. Are you thinking it should cancel the merge entirely?

**Comment by maxneal** [comment]
Cancelling the save should NOT result in a completed merge.

**Comment by maxneal** [comment]
To clarify, canceling the save-out shouldn't remove the merging task entirely, it should just cancel the save-out process. So if a user hits "Merge" then realizes they need to change a semantic resolution decision or edit something in the merge conflicts dialog, they should still be able to make those changes and try merging again.

**Comment by thompsct** [comment]
I moved the saveas dialog to before the merge executes. Canceling it will cancel the merge.
