### ISSUE TITLE
Nodes should remain highlighted after extraction and graph shouldn't move

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#255]
To reproduce:

- View CV model PhysioMap
- Select a set of nodes and extract them using "Extract Selected" right-click menu option
- Selected nodes become un-highlighted and the graph starts adjusting node positions

Nodes should remain highlighted and the graph shouldn't start moving around again.

**Comment by maxneal** [comment]
There is also a related bug that I found where groups of unselected nodes move together when you attempt to drag one node around. 

- Open CV model
- View PhysioMap
- Select all nodes in the graph except "Blood flow through mitral valve" and "Portion of blood in left atrium"
- Right click on a selected node and hit "Extract Unselected"
- Now attempt to drag one of the nodes that were selected in the large ring of the PhysioMap

All the previously selected nodes (which are no longer highlighted) are dragged together instead of the single node. 
The correct behavior here is that after the extraction is performed, the selected nodes should remain selected, and any time a single node is selected and dragged, only that node should move.

**Comment by thompsct** [comment]
Fixed the bug where one node was getting excluded.

**Comment by thompsct** [comment]
Selected nodes weren't being highlighted after an update. That's fixed. Second, I added an option to disable the function that runs the simulation briefly even if 'fix nodes' is set.

**Comment by maxneal** [comment]
Where in the GUI can I set this option to disable the post-extraction graph activity?

**Comment by thompsct** [comment]
I hard-coded it. I'm not sure what causes the simulation to run for a second or two after updating. I'm concerned it's built into D3.

**Comment by maxneal** [comment]
Confirmed the fix for the node selection. But the graph still moves when I perform an extraction on my end. i.e. I don't see a change in behavior.

**Comment by thompsct** [comment]
I set the simulation to set for 25 seconds if nodes are fixed and an extraction is added. The delay can't be too much below that or the graph doesn't load properly.
