### ISSUE TITLE
Remove extraction scissors from Project Tab GUI

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#258]
Dragging nodes onto the scissors icon doesn't seem to do anything, and since the desired functionality is provided by the context menu item "Extract unselected", let's remove the scissors for now.

**Comment by thompsct** [comment]
I removed this, but need to do some menu changes to nodes within an extraction.

**Comment by thompsct** [comment]
Added a remove option to the context menu for nodes within an extraction.
