### ISSUE TITLE
Closing a model in a Project Tab that is used in an Active Task throws Null Pointer Exception

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#259]
If you load the CV and BARO models and start a merging task, then return to the main Project Tab interface and close one of the models, SG throws a Null Pointer Exception when you click on the merging task in the Active Task tray. 

This does not seem to affect the ability to perform the merge and save out the merged model, but if you perform the merge multiple times using the same active task, you cannot add the resulting merged model to the main Project Tab interface following the merge.

**Comment by thompsct** [comment]
Fixed this and several related bugs.
