### ISSUE TITLE
"Select Node Inputs" doesn't seem to do anything when viewing a PhysioMap

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#261]
The "Select Node Inputs" context menu item works as expected for Dependency maps but doesn't seem to do anything for PhysioMaps. When you select this item, any node that has an arrow directed towards the selected node should become highlighted/selected.

You can use the CV model to reproduce. View the PhysioMap, select the "Portion of blood in Cavity of right ventricle" node, right click and hit "Select Node Inputs." The "Blood flow through tricuspid valve" node should be selected/highlighted but it is not.

**Comment by thompsct** [comment]
Fixed.

**Comment by maxneal** [comment]
This works if you have a physical process node selected and then hit "Select node inputs" but it doesn't do anything if you perform the same action on a physical entity node.

If there is an arrow from process A to entity B and you "Select node inputs" for entity B, then process A should be selected. Clicking this menu item should highlight any nodes with an arrow to the node you've right-clicked on (or if you've got a set of nodes highlighted, nodes with arrows to the highlighted set).

**Comment by thompsct** [comment]
Oop, fixed this.
