### ISSUE TITLE
window pop under

### ISSUE THREAD

**Issue by carlsonbrian** [SemBioProcess/SemGen#267]
When I go to create a new custom term a window opens that allows me to name that term but if I have to indicate partonomy with the + button the window of available terms pops under the current window. This also happens when I am searching or adding terms as sources or sinks while creating a custom process.
<img width="1440" alt="screen shot 2017-10-20 at 2 14 12 pm" src="https://user-images.githubusercontent.com/32965817/31835839-24aaff32-b5a1-11e7-9d06-d8557016a36d.png">

**Comment by maxneal** [comment]
We haven't been able to reproduce this bug in SemGen 4.1.0 beta or the current development branch. We've tried on Mac and Windows machines. We suspect the issue was fixed sometime prior to release of the 4.1.0 beta version.
