### ISSUE TITLE
Need to make sure that all FMA IDs used in previously annotated models are up to date

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#270]
For example, I noticed that "Portion of blood" in the Smith_2004 model that comes with the SG distribution uses an outdated FMA ID.

**Comment by GrahamKim** [comment]
Old URIs (`http://sig.uw.edu/fma#some_name`) should be changed to new URIs (`http://purl.org/sig/ont/fma/fma00000`) in the example models.

**Comment by GrahamKim** [comment]
Old FMA IDs replaced with new ones in master branch.
