### ISSUE TITLE
SBML and CellML need to be written out in UTF-8 format

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#273]
I've had errors show up when exporting to an SBML file, then trying to re-open in SemGen. Seems that the SBML reader encounters an invalid UTF-8 character encoding (the accented "e" in Nicolas LeNovere's last name, which is always included in SBML models from BioModels b/c of the bibliographic reference to the BioModels paper).

**Comment by GrahamKim** [comment]
Hmm. I'm not able to reproduce this issue. When I try exporting to SBML, the file is already encoded in UTF-8 and SemGen can read "Le Novère N". @maxneal is there a specific model or steps that causes this issue?

**Comment by maxneal** [comment]
I'll send you an example model where that you can use to reproduce the bug. Things might work OK in the master branch, but I'm seeing the problem in the COMBINEarchive branch that includes lots of updates to the way files are read and written so please test it on that branch.

**Comment by maxneal** [comment]
Fixed in commit 4b5062423fe2fecfc9156ce271eb7ac58ac45702
