### ISSUE TITLE
ModelAccessor for string?

### ISSUE THREAD

**Issue by 0u812** [SemBioProcess/SemGen#309]
Hi all, it would be useful for Tellurium interop to pass a string of raw SBML content instead of a file. It looks like there currently isn't a ModelAccessor for a string, correct?

**Comment by maxneal** [comment]
This functionality has been added to the SemSim code base. Needs some additional testing. Kyle if you could build a new version of the API and try this out, that would be awesome.

Example usage:
```
ModelAccessor test = FileAccessorFactory.getModelAccessorForString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + 
				"<sbml xmlns=\"http://www.sbml.org/sbml/level2/version4\" level=\"2\" version=\"4\">\n" + 
				"<model id=\"BIOMD0000000001\" name=\"Edelstein1996 - EPSP ACh event\" metaid=\"_000001\">\n" +
				"</model>\n" + "</sbml>", ModelType.SBML_MODEL);
		
SemSimModel ssm = new SBMLreader(test).read();
System.out.println(ssm.getMetadataID());
```

**Comment by 0u812** [comment]
This appears to be working great, thanks Max!
