### ISSUE TITLE
SemGen logo looks rough in application

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#43]
When running SG, the SG logo that appears in the upper left of the application looks like a fuzzy blue insect. Seems like the program is attempting to resize a larger image and isn't able to represent the logo faithfully.

Also, the logo that appears in the Windows taskbar appears slightly pixelated, unaliased, roughened.

We should fix before Auckland, since so many sets of eyes will be on SG then.

**Comment by thompsct** [comment]
I changed it over to the method that takes a list of icons. The top left looks better. I don't know if it's possible to improve the tray icon without making a new image (it actually looked good to me before, but I don't know what it looks like blown up).

**Comment by maxneal** [comment]
Brought in the changes to the master branch (including cfg folder) but icon in top left looks the same on my end. 
Making a new image wouldn't be too hard. Maybe we just need to figure out what dimensions it needs to be in and in what format (jpg, gif, png, etc)?

**Comment by thompsct** [comment]
The to left icon may need to be simplified as well. If worse comes to worse, we can always change it back to the default Java icon.

**Comment by maxneal** [comment]
Now that I think about it, I believe the better place to set the application icon is actually when you make the .exe or .app wrapper for the executable jar file. So let's not monkey with the icon for the local builds of the executable jar file. Let's change things back to the default Java icon.

**Comment by thompsct** [comment]
I think that just sets the icon for the executable. The taskbar and corner have to be set within Java.

**Comment by maxneal** [comment]
OK. Let's just leave it as the default java icon for now. If one of us has time to address this before Auckland, great. But if not, that's fine.

**Comment by thompsct** [comment]
I've commented out the relevant line.

**Comment by maxneal** [comment]
Fixed in commmit a63146f3de1bdb07e5164f03bda009e03b87eb64
