### ISSUE TITLE
Improve feedback when a model fails to load.

### ISSUE THREAD

**Issue by thompsct** [SemBioProcess/SemGen#72]
Currently, when a model fails to load, the user is not informed in most cases; instead, the progress bar disappears and nothing happens.

**Comment by maxneal** [comment]
Excellent idea.

**Comment by maxneal** [comment]
Now, when a model fails to load, an error message that says "XXXX was an invalid model" is usually shown to the user. But if we can provide more specific reasons, we should.

**Comment by maxneal** [comment]
SemGen should now show the more specific errors that are added to a model when there is a problem reading them in.
