### ISSUE TITLE
Create helpful hints indicating the scope of reference ontologies in ReferenceClassFinderPanel

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#97]
In the current draft of the PHN paper we state the following scope for our reference ontologies.

Foundational Model of Anatomy (FMA): Macromolecular to organism-level anatomy
Mouse Adult Gross Anatomy (MA): Rodent-specific anatomy
Cell Type Ontology (CL): Non-mammalian cell types
Gene Ontology:cellular component (GO-cc): Macromolecular structures not represented in the FMA
Protein Ontology (PR): Proteins
Chemical Entities of Biological Interest (ChEBI): Atoms and small molecules
Ontology for Biomedical Investigations (OBI): Laboratory materials

We want to indicate the scope when the the user selects a reference ontology from a drop-down list, as in ReferenceClassFinderPanel

**Comment by thompsct** [comment]
Actually, I think it might be a good idea to provide short descriptions for all of our ontologies.
The remaining ones are: CMO, OPB, PATO, SBO, and SNOMED.

**Comment by thompsct** [comment]
I added descriptions to the reference ontologies which show up in the reference term search dialog.

**Comment by maxneal** [comment]
A few suggestions:

* Start each hint with something like "For annotating " ?
* Reduce the font size of the hint by 1 and make it in italics? Maybe make the font color dark gray to indicate it's a hint?
* Align the left edge of the hint with the left edge of the combobox showing the ontology name.
* Increase the space below the hint a bit

And here are hints for the remaining ontologies:

OPB: physical properties and dependencies
PATO: phenotypes and traits not represented as properties in the OPB
SBO: physical dependencies not in the OPB
SNOMED: clinical-domain physical properties not in the OPB

I don't think we need to preserve the CMO in our list. SNOMED probably covers the bases we need. Plus I'm not convinced the CMO subclasses things in a way that jibes with the OPB view.

**Comment by maxneal** [comment]
The background behind the combobox and hints is now SG blue. Can you revert back to gray?
Also, the alignment of the hint looks good except for when I first open the dialog. WHen I go through and select the different ontologies, the alignment clicks in.  Also, could you increase the space between the hint and the components below a teeny bit more?  And use all lower-case characters after "For annotating..." Thanks!

**Comment by thompsct** [comment]
Check out the newest commit.

**Comment by maxneal** [comment]
The only very minor thing I see is that the GUI elements below the hint shift around a little each time a different ontology is selected in the combobox. If we can fix this before the 3.0 release date, great. If not, I'm OK rolling with it as-is. I'll make this a 3.1 issue for now.

**Comment by maxneal** [comment]
This is all looking good now.
